name: Check banned function

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  banned-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Create binary
        run: |
          exit_status=$(make)
          if [ exit_status == 1 ]; then
            echo "::error ::Build ERROR"
            exit 1

      - name: Check for banned functions
        run: |
          if [ -f allowed_function.note ]; then
            allowed_functions=$(cat allowed_function.note)
          else
            allowed_functions=""
            echo "::warning ::Warning: allowed_function.note not found. All banned functions will be considered illegal."
          fi
          echo $(ls)
          banned_functions=$(nm -C binary | grep GLIBC | grep -v "__" || true)

          if [ -n "$banned_functions" ]; then
            while IFS= read -r function; do
              if [ -n "$allowed_functions" ]; then
                if ! echo "$allowed_functions" | grep -qw "$function"; then
                  echo "::error file=./binary::Banned function detected: $function"
                fi
              else
                echo "::error file=./binary::Banned function detected: $function"
              fi
            done <<< "$banned_functions"
            exit 1
          else
            echo "::notice ::No banned functions found."
          fi
