name: Build checker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Try to compile project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Try to make
        run: make

      - name: Try to clean
        run: make clean

      - name: Try to fclean
        run: make fclean

      - name: Try to re
        run: make re
