name: Coding style checker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
    checker:
      runs-on: ubuntu-latest
      container: ghcr.io/epitech/coding-style-checker:latest

      steps:
        - name: Checkout the code
          uses: actions/checkout@v4
        
        - name: Run checker
          run: |
            check.sh $(pwd) $(pwd)
            CSERR=$(cat $(pwd)/coding-style-reports.log)
            while IFS= read -r ERR; do
              str=$(echo $ERR | sed 's/:/\n/g')
              echo "::error file=${str[1]#./},title=${str[3]#./} coding style errors detected: ${str[2]#./}::${str[4]#./}"
            done <<< "$CSERR"
            if [[ -n $CS ]]; then
              exit 1
            else
              echo No coding style errors detected
            fi