name: Coding Style Checker

on:
  push:
    branches:
      - "main"
  pull_request:


jobs:
  check_coding_style:
    name: "Check coding styles error"
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest

    steps:
      - uses: actions/checkout@v4
      - id: coding_style
        run: |
          check.sh $(pwd) $(pwd)
          CODING_STYLE_ERRORS=$(cat $(pwd)/coding-style-reports.log)
          while IFS= read -r ERROR
            do
            array=(`echo $ERRORS | sed 's/:/\n/g'`)
            echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
          done
          if [[ -n $CODING_STYLE_ERRORS ]]
          then
            exit 1
          else
            echo No coding style errors detected
          fi
  