name: Coding Style Checker

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  check_coding_style:
    name: "Check coding styles error"
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest

    steps:
      - uses: actions/checkout@v4

      - name: Process coding style checker
        shell: bash
        run: |
          check.sh $(pwd) $(pwd)
          if [ -s "$(pwd)/coding-style-reports.log" ]; then
              while IFS= read -r ERROR
              do
                  array=(`echo $ERROR | sed 's/:/\n/g'`)
                  echo "::error file=${array[0]#./},line=${array[1]}, title=${array[2]} coding style errors detected: ::${array[3]}"
              done < "$(pwd)/coding-style-reports.log"
              exit 1
          else
              echo "::success No coding style errors detected"
          fi