name: Coding style checker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
    checker:
      runs-on: ubuntu-latest
      container: ghcr.io/epitech/coding-style-checker:latest

      steps:
        - name: Checkout the code
          uses: actions/checkout@v4
        
        - name: Run checker
          run: |
            check.sh $(pwd) $(pwd)
            CODING_STYLE_ERRORS=$(cat $(pwd)/coding-style-reports.log)
            for ERRORS in $CODING_STYLE_ERRORS; do
              array=(`echo $ERRORS | sed 's/:/\n/g'`)
              echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
            done
            if [[ -n $CODING_STYLE_ERRORS ]]
            then
              exit 1
            else
              echo No coding style errors detected
            fi
