name: Repository mirroring

on:
  push:
    branches-ignore:
      'ga-ignore-*'
  pull_request:
    branches-ignore:
      'ga-ignore-*'

env:
  MIRROR_URL: ${{ vars.MIRROR_URL }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create SSH Key
        run: |
            mkdir -p ~/.ssh
            echo "${{ env.SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
    
      - name: Remove .github directory (if present)
        run: git rm -rf --cached .github || echo ".github not found, skipping removal"

      - name: Verify Repository
        run: |
          git fsck --full || echo "Git fsck completed with warnings"
          git gc || echo "Git gc completed with warnings"

      - name: Push to mirror
        run: |
          git remote add mirror ${{ env.MIRROR_URL }}
          git fetch --all
          git push --mirror --prune --force-with-lease mirror origin
          echo "Files pushed to mirror:"
          git ls-files