name: Repository size

on: 
  push:
    branches-ignore:
    - 'ga-ignore-*'
  pull_request:
    branches-ignore:
    - 'ga-ignore-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Echo env var
        run: echo ${{ github.ref_name }}

      - name: Print repo size
        run: echo `du -skh --exclude=".git"`