name: Repository mirroring

on:
  push:
    branches-ignore:
      'ga-ignore-*'
  pull_request:
    branches-ignore:
      'ga-ignore-*'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add remote
        run: git remote add mirror ${{ vars.MIRROR_URL }}
    
      # - name: Remove .github
      #   run: git rm -rf .github

      - name: Push on mirror
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.GIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git rm -rf .github
            git push --tags --force mirror "refs/remotes/origin/*:refs/heads/*" --no-verify
            echo `git ls-files`