name: Repository mirroring

on:
  push:
    branches-ignore:
      'ga-ignore-*'
  pull_request:
    branches-ignore:
      'ga-ignore-*'

env:
  MIRROR_URL: ${{ vars.MIRROR_URL }}
  SSH_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create SSH Key
        run: |
            mkdir -p ~/.ssh
            echo "${{ env.SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
    
      - name: Remove .github
        run: git rm -rf --cached .github

      - name: Verify Repository
        run: |
            git fsck
            git gc

      - name: Push on mirror
        run: |
            git remote add mirror ${{ env.MIRROR_URL }}
            git push --mirror --prune --force-with-lease
            echo `git ls-files`
