name: Repository mirroring

on:
  push:
    branches-ignore:
      'ga-ignore-*'
  pull_request:
    branches-ignore:
      'ga-ignore-*'



jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Define SSH Key
        run: export GIT_SSH_COMMAND="ssh -v -i ${{ secrets.GITHUB_TOKEN }} -o StrictHostKeyChecking -l ${{ github.actor }}"

      - name: Add remote
        run: git remote add mirror ${{ vars.MIRROR_URL }}
    
      - name: Remove .github
        run: rm -rf .github

      - name: Push on mirror
        run: git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"