name: Repository mirroring

on:
  push:
    branches-ignore:
      'ga-ignore-*'
  pull_request:
    branches-ignore:
      'ga-ignore-*'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create SSH Key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.GIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
    
      - name: Remove .github
        run: git rm -rf --cached .github

      - name: Verify Repository
        run: |
            git fsck
            git gc

      - name: Push on mirror
        run: |
            git fetch --all
            git push --mirror --prune --force-with-lease ${{ vars.MIRROR_URL }}
            echo `git ls-files`
