name: "What time is it"

on:
  push:
    branches-ignore:
      'ga-ignore-*'
  pull_request:
    branches-ignore:
      'ga-ignore-*'

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Echo the date
      run: echo `date`
